# Generated by Django 2.2.5 on 2022-09-05 02:59

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=100)),
                ('searchType', models.CharField(choices=[('yahoo-Finance', 'yahoo-Finance'), ('EDGAR-Search', 'EDGAR-Search')], max_length=15)),
                ('tickerSymbol', models.CharField(max_length=50)),
                ('CIK', models.CharField(blank=True, max_length=10, null=True)),
            ],
            managers=[
                ('Reports', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='UpdateReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Brother_EDGAR.Report')),
            ],
            managers=[
                ('UpdateReports', django.db.models.manager.Manager()),
            ],
        ),
    ]
